name: Deploying
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: BBS
    if: ${{ github.repository_owner == 'PojavLauncherTeam' }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        run: |
          cd /home/kremix/PojavBot
          git pull

      - name: Deployment
        env:
          password: ${{ secrets.BBS_SECRET }}
        run: |
          yarn compile
          echo $password | sudo -S systemctl restart PojavBot
