name: Testing
on:
  - push
  - pull_request

jobs:
  build:
    name: Build bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies and compile code
        run: yarn --immutable
