name: Testing
on:
  - push
  - pull_request

jobs:
  cancel:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.10.0
      with:
        access_token: ${{ github.token }}

  build:
    name: Build bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Expose yarn config as "$GITHUB_OUTPUT"
        id: yarn-config
        shell: bash
        run: |
          echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-download-cache
        with:
          path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
          key: yarn-download-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-download-cache-

      - name: Restore yarn install state
        id: yarn-install-state-cache
        uses: actions/cache@v3
        with:
          path: .yarn/ci-cache/
          key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

      - name: Install dependencies and compile code
        shell: bash
        run: |
          yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NM_MODE: 'hardlinks-local'
          YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz

  deploy:
    name: Deployment
    runs-on: BBS
    if: ${{ github.repository_owner == 'PojavLauncherTeam' }}
    steps:
      - name: Deployment
        env:
          password: ${{ secrets.BBS_SECRET }}
        run: |
          cd /home/kremix/PojavBot
          yarn pull-reset
          echo $password | sudo -S systemctl restart PojavBot
